# Задание 1

Массив A состоит из целых положительных чисел ­ длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно составить треугольник с положительной площадью ­ функция возвращает 0.

In [2]:
import random
import time
import numpy as np
from heapq import *
import copy

In [38]:
arr = np.random.randint(1, 20, 10)
arr
maxP = 0

for i in range(len(arr) -1):
    for j in range(len(arr) - (i + 1)):
            if arr[j] > arr[j+1]:
                t = arr[j+1]
                arr[j+1] = arr[j]
                arr[j] = t

for i in range(len(arr)-1, 2, -1):
    if(arr[i] < arr[i-1] + arr[-2]):
        maxP = arr[i] + arr[i-1] + arr[i-2]
        break
                
            
print(arr)        
print(maxP)

[ 2  3  4  7 12 14 16 17 18 19]
54


# Задание 2

Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы вместе они образовали максимально возможное число. Замечание: Результат может быть очень большим числом, поэтому представьте его как string, а не integer.

In [8]:
##Сравнивает два числа и возвращает true если a лучше b
def comparison(a, b):
    a_str = str(a)
    b_str = str(b)
    while len(a_str) > 0 and len(b_str) > 0:
        if int(a_str[0]) > int(b_str[0]):
            return True
        elif int(b_str[0]) > int(a_str[0]):
            return False
        a_str = a_str[1:]
        b_str = b_str[1:]
    if len(a_str) == 0 and len(a_str) != 0:
        if(int(b_str[0]) > int(str(a)[0])):
            return False
        return True
    elif len(b_str) == 0 and len(a_str) != 0:
        if(int(a_str[0]) > int(str(b)[0])):
            return True
        return False
    return False
        
        
arr = np.random.randint(1, 100, 20)
print(arr)
for i in range(len(arr) - 1):
    for j in range(len(arr) - 1):
            if not(comparison(arr[j], arr[j+1])):
                t = arr[j+1]
                arr[j+1] = arr[j]
                arr[j] = t

result = ""
for i in range(len(arr)):
    result += str(arr[i])
print(result)

[55 79 69  4 70 97 86 92 36 82 80 46 59 60 44 66 52  4 79 21]
97928682807979706966605955524644443621


# Задание 3

Дана матрица mat размером m * n, значения ­ целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [92]:
w = int(input())
h = int(input())
matrix = np.random.randint(0, 11, (w, h))
print(matrix)
print("_________________________________")
diag = min(w, h)
for i in range(diag):
    for j in range(diag - 1):
        if(matrix[j][j] > matrix[j+1][j+1]):
            matrix[j][j], matrix[j+1][j+1] = matrix[j+1][j+1], matrix[j][j]
        if(matrix[j][h-j-1] > matrix[j+1][h-j-2]):
            matrix[j][h-j-1], matrix[j+1][h-j-2] = matrix[j+1][h-j-2], matrix[j][h-j-1]
print(matrix)

5
7
[[ 5  0  3  2  3  2  4]
 [ 5  0  5  6  7  0  9]
 [ 9  4  3 10  2  3  4]
 [10  9  3  3  9  8  5]
 [ 8  6  2 10  8  9  8]]
_________________________________
[[ 0  0  3  2  3  2  0]
 [ 5  2  5  6  7  2  9]
 [ 9  4  3 10  3  3  4]
 [10  9  3  4  9  8  5]
 [ 8  6  5 10  8  9  8]]
