# Лабораторная работа №1
## Выполнил студент группы БВТ2004 Абрамов Кирилл Владиславович

### Оглавление
1. [Задание 1](#Задание-№1)
2. [Задание 2](#Задание-№2)
3. [Задание 3](#Задание-№3)
4. [Вывод](#Вывод)

### Задание №1
<i> Вызвать функцию print() и передать туда строку Hello, World! </i>

In [1]:
print("Hello, World!")

Hello, World!


### Задание №2
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры <b>m</b>, <b>n</b>, <b>min_limit</b>, <b>max_limit</b>, где <b>m</b> и <b>n</b> указывают размер
матрицы, а <b>min_lim</b> и <b>max_lim</b> - минимальное и максимальное значение для
генерируемого числа.

In [18]:
import random
import time
import numpy as np
import heapq
import copy

In [36]:
user_m = int(input())
user_n = int(input())
user_min_limit = int(input())
user_max_limit = int(input())
user_m, user_n, user_min_limit, user_max_limit

20
20
1
50


(20, 20, 1, 50)

In [37]:
matric = np.random.randint(user_min_limit, user_max_limit+1, (user_n, user_m))
matric

array([[10, 38, 38,  3, 21, 39, 25, 44,  2, 25, 17, 42, 20, 15, 30, 43,
        32,  8, 18, 22],
       [19,  5,  9, 10, 14,  9, 37, 27,  3,  7, 12, 24, 42,  2, 46, 22,
        46, 23, 43, 40],
       [33, 19, 17, 32, 15, 12, 44, 17, 25,  8,  7, 18, 13, 50, 35, 29,
        49,  1, 49, 16],
       [11, 34, 12, 47,  3, 17,  7, 27, 26, 12, 36, 17, 30, 36, 29, 50,
        44,  3, 44, 10],
       [16,  1, 17,  1, 27, 13, 38, 10, 17, 18,  7, 43, 48, 37, 23, 37,
        11, 30, 40, 36],
       [13, 46, 43, 48, 35, 46, 44,  7, 45, 38, 27, 50, 14, 50,  9, 35,
        25, 45,  8, 44],
       [ 9, 42, 37, 47, 26,  4, 22, 34, 14, 32, 13, 42, 15, 31,  5, 17,
        13, 17,  9, 37],
       [28, 18, 38, 34,  7, 45,  1, 19, 22, 21,  1, 41, 21, 20, 50, 39,
        48, 23, 44, 11],
       [29, 32, 35, 14, 32, 29,  3, 26, 36, 15, 31, 16, 22, 25,  1, 43,
         6, 21,  4,  2],
       [17, 27, 15, 11, 36, 34, 35, 23, 19, 37,  1, 40, 50, 33, 44, 40,
         6, 24,  8, 11],
       [39, 19, 16, 10, 26, 14

### Задание №3
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [14]:
# Сортировка выбором.
# Берётся срез массива, в котором минимальный элемент переносят в самый левый угол,
# после чего срез уменьшается и цикл повторяется.
m = copy.copy(matric)
start_time = time.time()
for arr in m:
    for i in range(len(arr) -1):
        min = i
        for j in range(i+1, len(arr)):
            if arr[j] < arr[min]:
                min = j
        t = arr[min]
        arr[min] = arr[i]
        arr[i] = t
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))
m = np.matrix(sorted(map(tuple, m)))
m

--- 0 ms ---


matrix([[1, 1, 1, 6, 8],
        [2, 6, 7, 8, 8],
        [3, 4, 5, 7, 9],
        [3, 6, 6, 8, 8],
        [3, 6, 7, 8, 8]])

In [16]:
# Сортировка вставкой.
m = copy.copy(matric)
start_time = time.time()
for arr in m:
    for i in range(1, len(arr)):
        for j in range(i, 0, -1):
            if arr[j] < arr[j-1]:
                t = arr[j]
                arr[j] = arr[j-1]
                arr[j-1] = t
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

m = np.matrix(sorted(map(tuple, m)))
m

--- 0 ms ---


matrix([[1, 1, 1, 6, 8],
        [2, 6, 7, 8, 8],
        [3, 4, 5, 7, 9],
        [3, 6, 6, 8, 8],
        [3, 6, 7, 8, 8]])

In [19]:
# Сортировка обменом. || Сортировка пузырьком.
m = copy.copy(matric)
start_time = time.time()
for arr in m:
    for i in range(len(arr) -1):
        for j in range(len(arr) - (i + 1)):
            if arr[j] > arr[j+1]:
                t = arr[j+1]
                arr[j+1] = arr[j]
                arr[j] = t
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

m = np.matrix(sorted(map(tuple, m)))
m

--- 0 ms ---


matrix([[1, 1, 1, 6, 8],
        [2, 6, 7, 8, 8],
        [3, 4, 5, 7, 9],
        [3, 6, 6, 8, 8],
        [3, 6, 7, 8, 8]])

In [29]:
# Сортировка Шелла.
m = copy.copy(matric)
start_time = time.time()

for arr in m:
    diap = len(arr)//2
    while diap > 0:
        for i in range(len(arr)-diap+1):
            for j in range(i, diap-1, -diap):
                if (arr[j-diap] > arr[j]):
                    t = arr[j-diap]
                    arr[j-diap] = arr[j]
                    arr[j] = t
        diap = diap // 2

print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

m = np.matrix(sorted(map(tuple, m)))
m

--- 1 ms ---


matrix([[1, 2, 4, 7, 8, 9],
        [2, 3, 5, 5, 8, 9],
        [3, 3, 5, 6, 7, 8],
        [3, 3, 5, 8, 9, 9],
        [3, 4, 5, 6, 6, 7],
        [3, 4, 5, 6, 7, 9]])

In [26]:
# Быстрая сортировка.
def my_sort(arr):
    if(len(arr) <= 1):
        return arr
    e = arr[-1]
    l = list(filter(lambda x: x < e, arr))
    r = list(filter(lambda x: x > e, arr))
    c = list(filter(lambda x: x == e, arr))
    
    return my_sort(l) + c + my_sort(r)


m = copy.copy(matric)
start_time = time.time()

for i in range(len(m)):
    m[i] = my_sort(m[i])


print("--- {0} ms ---".format(((time.time() - start_time)*1000)))

m = np.matrix(sorted(map(tuple, m)))
m

--- 0.0 ms ---


matrix([[ 1,  1,  4,  4,  6,  9,  9],
        [ 1,  3,  3,  5,  6,  6,  8],
        [ 1,  3,  3,  5,  6, 10, 10],
        [ 2,  4,  4,  5,  6,  8, 10],
        [ 3,  3,  4,  6,  8,  9, 10],
        [ 3,  4,  4,  4,  6,  7, 10],
        [ 5,  5,  6,  7,  7,  9, 10]])

In [42]:
# Турнирная сортировка.
start_time = time.time()
# Турнирная сортировка с многопутевым слиянием.


m = copy.copy(matric).tolist()

MAX_SIZE = 7

def multipath_merge(a: list, b: list) -> list:
    result = []
    
    while len(a) > 0 and len(b) > 0:
        if (b[0] < a[0]):
            result.append(b.pop(0))
        else:
            result.append(a.pop(0))
            
    len_a = len(a)
    len_b = len(b)
    
    if (len_a == 0 and len_b == 0):
        return result
    
    if (len_a > 0):
        result += a
    else:
        result += b
                
    return result

def optimal_tournament_sort(values: list) -> list:
    heap = []
    
    for i in values:
        heappush(heap, i)
        
    for i in range(len(heap)):
        values[i] = heappop(heap)
    
    return values

                
def bracketize(values: list) -> list:
    heap = []
    
    while len(heap) <= MAX_SIZE:
        heappush(heap, values.pop(0))
        
    winners = []
    losers = []
    
    while len(values) > 0:
        if len(winners) == 0:
            winners.append(heappop(heap))
            
        if values[0] > winners[-1]:
            heappush(heap, values.pop(0))
        else:
            losers.append(values.pop(0))
            
        if len(heap) > 0:
            winners.append(heappop(heap))
            
    while len(heap) > 0:
        winners.append(heappop(heap))
        
    if len(losers) == 0:
        return winners
    
    return multipath_merge(tournament_sort(losers), winners)

def tournament_sort(values: list) -> list:
    if (len(values) <= MAX_SIZE):
        return optimal_tournament_sort(values)
    else:
        return bracketize(values)


start_time = time.time()

for i in range(len(m)):
    m[i] = tournament_sort(m[i])
    
m = np.matrix(sorted(map(tuple, m)))
    
print("--- {:.6f} ms ---".format((time.time() - start_time) * 1000))
m

--- 0.000000 ms ---


matrix([[ 1,  1,  7, 10, 11, 13, 16, 17, 17, 18, 23, 27, 30, 36, 37, 37,
         38, 40, 43, 48],
        [ 1,  1,  7, 11, 18, 19, 20, 21, 21, 22, 23, 28, 34, 38, 39, 41,
         44, 45, 48, 50],
        [ 1,  2,  3,  4,  6, 14, 15, 16, 21, 22, 25, 26, 29, 29, 31, 32,
         32, 35, 36, 43],
        [ 1,  5,  9,  9, 12, 14, 18, 18, 23, 24, 30, 30, 31, 33, 33, 35,
         43, 43, 46, 49],
        [ 1,  6,  7,  9, 17, 18, 21, 22, 23, 29, 30, 30, 31, 33, 34, 41,
         41, 42, 44, 48],
        [ 1,  6,  8, 11, 11, 15, 17, 19, 23, 24, 27, 33, 34, 35, 36, 37,
         40, 40, 44, 50],
        [ 1,  7,  8, 12, 13, 15, 16, 17, 17, 18, 19, 25, 29, 32, 33, 35,
         44, 49, 49, 50],
        [ 2,  3,  4,  5,  9, 16, 20, 20, 22, 29, 30, 31, 32, 38, 40, 41,
         41, 47, 49, 50],
        [ 2,  3,  5,  7,  9,  9, 10, 12, 14, 19, 22, 23, 24, 27, 37, 40,
         42, 43, 46, 46],
        [ 2,  3,  8, 10, 15, 17, 18, 20, 21, 22, 25, 25, 30, 32, 38, 38,
         39, 42, 43, 44],
        [ 

### Вывод
