# Лабораторная работа №1
## Выполнил студент группы БВТ2004 Абрамов Кирилл Владиславович

### Оглавление
1. [Задание 1](#Задание-№1)
2. [Задание 2](#Задание-№2)
3. [Задание 3](#Задание-№3)
4. [Вывод](#Вывод)

### Задание №1
<i> Вызвать функцию print() и передать туда строку Hello, World! </i>

In [1]:
print("Hello, World!")

Hello, World!


### Задание №2
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры <b>m</b>, <b>n</b>, <b>min_limit</b>, <b>max_limit</b>, где <b>m</b> и <b>n</b> указывают размер
матрицы, а <b>min_lim</b> и <b>max_lim</b> - минимальное и максимальное значение для
генерируемого числа.

In [1]:
import random
import time
import numpy as np
from heapq import *
import copy

In [2]:
user_m = int(input())
user_n = int(input())
user_min_limit = int(input())
user_max_limit = int(input())
user_m, user_n, user_min_limit, user_max_limit

7
7
1
10


(7, 7, 1, 10)

In [3]:
matric = np.random.randint(user_min_limit, user_max_limit+1, (user_n, user_m))
matric

array([[ 2,  9,  3,  7,  7,  1,  6],
       [ 2,  7,  2,  3,  9, 10,  6],
       [ 5,  9, 10,  9,  8, 10, 10],
       [ 6,  5,  1,  4,  6,  7,  8],
       [ 9,  2,  5,  1,  2,  5,  2],
       [ 8,  5,  8,  7,  5,  6,  6],
       [ 7,  4,  7,  6,  4,  1,  6]])

### Задание №3
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [4]:
# Сортировка выбором.
# Берётся срез массива, в котором минимальный элемент переносят в самый левый угол,
# после чего срез уменьшается и цикл повторяется.
m = copy.copy(matric)
start_time = time.time()
for arr in m:
    for i in range(len(arr) -1):
        min = i
        for j in range(i+1, len(arr)):
            if arr[j] < arr[min]:
                min = j
        t = arr[min]
        arr[min] = arr[i]
        arr[i] = t
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))
m = np.matrix(sorted(map(tuple, m)))
m

--- 0 ms ---


matrix([[ 1,  2,  2,  2,  5,  5,  9],
        [ 1,  2,  3,  6,  7,  7,  9],
        [ 1,  4,  4,  6,  6,  7,  7],
        [ 1,  4,  5,  6,  6,  7,  8],
        [ 2,  2,  3,  6,  7,  9, 10],
        [ 5,  5,  6,  6,  7,  8,  8],
        [ 5,  8,  9,  9, 10, 10, 10]])

In [5]:
# Сортировка вставкой.
m = copy.copy(matric)
start_time = time.time()
for arr in m:
    for i in range(1, len(arr)):
        for j in range(i, 0, -1):
            if arr[j] < arr[j-1]:
                t = arr[j]
                arr[j] = arr[j-1]
                arr[j-1] = t
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

m = np.matrix(sorted(map(tuple, m)))
m

--- 0 ms ---


matrix([[ 1,  2,  2,  2,  5,  5,  9],
        [ 1,  2,  3,  6,  7,  7,  9],
        [ 1,  4,  4,  6,  6,  7,  7],
        [ 1,  4,  5,  6,  6,  7,  8],
        [ 2,  2,  3,  6,  7,  9, 10],
        [ 5,  5,  6,  6,  7,  8,  8],
        [ 5,  8,  9,  9, 10, 10, 10]])

In [6]:
# Сортировка обменом. || Сортировка пузырьком.
m = copy.copy(matric)
start_time = time.time()
for arr in m:
    for i in range(len(arr) -1):
        for j in range(len(arr) - (i + 1)):
            if arr[j] > arr[j+1]:
                t = arr[j+1]
                arr[j+1] = arr[j]
                arr[j] = t
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

m = np.matrix(sorted(map(tuple, m)))
m

--- 0 ms ---


matrix([[ 1,  2,  2,  2,  5,  5,  9],
        [ 1,  2,  3,  6,  7,  7,  9],
        [ 1,  4,  4,  6,  6,  7,  7],
        [ 1,  4,  5,  6,  6,  7,  8],
        [ 2,  2,  3,  6,  7,  9, 10],
        [ 5,  5,  6,  6,  7,  8,  8],
        [ 5,  8,  9,  9, 10, 10, 10]])

In [7]:
# Сортировка Шелла.
m = copy.copy(matric)
start_time = time.time()

for arr in m:
    diap = len(arr)//2
    while diap > 0:
        for i in range(len(arr)-diap+1):
            for j in range(i, diap-1, -diap):
                if (arr[j-diap] > arr[j]):
                    t = arr[j-diap]
                    arr[j-diap] = arr[j]
                    arr[j] = t
        diap = diap // 2

print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

m = np.matrix(sorted(map(tuple, m)))
m

--- 1 ms ---


matrix([[ 1,  2,  2,  2,  5,  5,  9],
        [ 1,  2,  3,  6,  7,  7,  9],
        [ 1,  4,  4,  6,  6,  7,  7],
        [ 1,  4,  5,  6,  6,  7,  8],
        [ 2,  2,  3,  6,  7,  9, 10],
        [ 5,  5,  6,  6,  7,  8,  8],
        [ 5,  8,  9,  9, 10, 10, 10]])

In [8]:
# Быстрая сортировка.
def my_sort(arr):
    if(len(arr) <= 1):
        return arr
    e = arr[-1]
    l = list(filter(lambda x: x < e, arr))
    r = list(filter(lambda x: x > e, arr))
    c = list(filter(lambda x: x == e, arr))
    
    return my_sort(l) + c + my_sort(r)


m = copy.copy(matric)
start_time = time.time()

for i in range(len(m)):
    m[i] = my_sort(m[i])


print("--- {0} ms ---".format(((time.time() - start_time)*1000)))

m = np.matrix(sorted(map(tuple, m)))
m

--- 0.0 ms ---


matrix([[ 1,  2,  2,  2,  5,  5,  9],
        [ 1,  2,  3,  6,  7,  7,  9],
        [ 1,  4,  4,  6,  6,  7,  7],
        [ 1,  4,  5,  6,  6,  7,  8],
        [ 2,  2,  3,  6,  7,  9, 10],
        [ 5,  5,  6,  6,  7,  8,  8],
        [ 5,  8,  9,  9, 10, 10, 10]])

In [9]:
# Турнирная сортировка.
start_time = time.time()
# Турнирная сортировка с многопутевым слиянием.


m = copy.copy(matric).tolist()

MAX_SIZE = 7

def multipath_merge(a: list, b: list) -> list:
    result = []
    
    while len(a) > 0 and len(b) > 0:
        if (b[0] < a[0]):
            result.append(b.pop(0))
        else:
            result.append(a.pop(0))
            
    len_a = len(a)
    len_b = len(b)
    
    if (len_a == 0 and len_b == 0):
        return result
    
    if (len_a > 0):
        result += a
    else:
        result += b
                
    return result

def optimal_tournament_sort(values: list) -> list:
    heap = []
    
    for i in values:
        heappush(heap, i)
        
    for i in range(len(heap)):
        values[i] = heappop(heap)
    
    return values

                
def bracketize(values: list) -> list:
    heap = []
    
    while len(heap) <= MAX_SIZE:
        heappush(heap, values.pop(0))
        
    winners = []
    losers = []
    
    while len(values) > 0:
        if len(winners) == 0:
            winners.append(heappop(heap))
            
        if values[0] > winners[-1]:
            heappush(heap, values.pop(0))
        else:
            losers.append(values.pop(0))
            
        if len(heap) > 0:
            winners.append(heappop(heap))
            
    while len(heap) > 0:
        winners.append(heappop(heap))
        
    if len(losers) == 0:
        return winners
    
    return multipath_merge(tournament_sort(losers), winners)

def tournament_sort(values: list) -> list:
    if (len(values) <= MAX_SIZE):
        return optimal_tournament_sort(values)
    else:
        return bracketize(values)


start_time = time.time()

for i in range(len(m)):
    m[i] = tournament_sort(m[i])
    
m = np.matrix(sorted(map(tuple, m)))
    
print("--- {:.6f} ms ---".format((time.time() - start_time) * 1000))
m

--- 0.000000 ms ---


matrix([[ 1,  2,  2,  2,  5,  5,  9],
        [ 1,  2,  3,  6,  7,  7,  9],
        [ 1,  4,  4,  6,  6,  7,  7],
        [ 1,  4,  5,  6,  6,  7,  8],
        [ 2,  2,  3,  6,  7,  9, 10],
        [ 5,  5,  6,  6,  7,  8,  8],
        [ 5,  8,  9,  9, 10, 10, 10]])

### Вывод
